reviews:
  namespace: fuse-bookinfo-prd
  image: ghcr.io/fxselazy/bookinfo-reviews
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: bookinfo.hellodolphin.in.th
  path: "/fuse/reviews(/|$)(.*)"
  # host: bookinfo.opsta.net
  # path: "/student46/reviews(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  RATINGS_SERVICE: http://bookinfo-prd-ratings:8081
  SERVICE_VERSION: v1
  ENABLE_RATINGS: "true"
  STAR_COLOR: blue