apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  name: {{ .Release.Name }}
  namespace: {{ .Values.reviews.namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: {{ .Values.ingress.path | default "/" }}
          pathType: Prefix
          backend:
            serviceName: {{ .Release.Name }}
            servicePort: {{ .Values.reviews.port }}